/*
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
*/

package main

import ("fmt")

func main() {

	var max_value int 
	var sum int = 2	
	var fib = [3] int {1,2,3}



	fmt.Println("Enter max value: ")
	fmt.Scan(&max_value)
	
	
	fmt.Println(max_value)
	
	for  fib[2] < max_value  {
		if fib[2] % 2 == 0  {
			sum += fib[2]	
			fmt.Println(fib[2])
		}
		
		fib[0] = fib[1]
		fib[1] = fib[2]
		fib[2] += fib[0]
		fmt.Println(fib)
	}
	fmt.Println("the sum of evens:")
	fmt.Println(sum)
}

